### ISSUE TITLE
[1.18.2] [Enhancement] Could you please add this enchant for mods that add paxels?

### ISSUE THREAD

**Issue by Zedrimar** [brnbrd/Auto-Smelt#2]
Forge: 40.1.0
Mod Ver: 1.2

As stated above, at the moment this mod does not count paxels as tools. I would highly appreciate it if there is a way to add paxels to the list of allowed tools (or at least allow anything with paxel in their item tag). 

One example mod if it helps, is gobber. Tried with other mods paxels though and those don't count either :/

**Comment by brnbrd** [comment]
Added with version 1.3
